//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> AdmissionNum { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string Subcast { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DOBInWords { get; set; }
        public string PreviousSchoolName { get; set; }
        public string AdmittedInClass { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string Progess { get; set; }
        public string Conduct { get; set; }
        public Nullable<System.DateTime> DateOfSchoolLeaving { get; set; }
        public string SchholLeftAtClass { get; set; }
        public string ReasonForLeavingSchool { get; set; }
        public string CertificateRecivedDate { get; set; }
        public string ReceivedBy { get; set; }
    }
}
